 publish = "public"

# Konfigurasi untuk saat di-upload ONLINE
[build]
  publish = "public"
  functions = "netlify/functions"

# Konfigurasi untuk functions
[functions]
  directory = "netlify/functions"